[[box-2]]
=== Box 2. GBIF Head of Delegation and Node Manager: roles and responsibilities
****
[discrete]
==== Head of Delegation

Following signature of the Memorandum of Understanding (MoU), new GBIF Participants are requested to nominate a Head of Delegation (HoD), to represent the country, economy or organization on the Governing Board, and to act as the Participant’s primary focal point for all GBIF-related activity.

The specific responsibilities of the HoD include:

* Attending Governing Board meetings held annually, usually in September or October. If the HoD is not able to attend, he/she can appoint a temporary HoD to attend the meeting.
* Nominating additional delegates to attend Governing Board meetings (a maximum of two additional delegates may attend each meeting, ideally including the Node Manager); informing the Secretariat prior to each meeting about the composition of the delegation.
* Preparing for such meetings by reading and consulting as appropriate on key documents submitted for approval by the Governing Board, such as the work programme, budget and strategic decisions. All documentation is distributed one month in advance of the meeting.
* Responding to intersessional communications from the Secretariat and Governing Board Chair between Governing Board meetings, including consultations, calls for award nominations and other requests for which actions or views are sought from Participants.
* In the case of Voting Participants, exercising the Participant’s vote at Governing Board meetings, including in elections for chairs and vice-chairs of the Governing Board and advisory committees; and responding to calls for nominations for such posts.
* Within the country or organization of the Participant, leading the strategic direction of GBIF participation, including oversight of the Participant node and ensuring it has adequate mandate and resourcing to carry out its core functions.
* For country Participants, maintaining good communications with appropriate government departments and agencies, including national focal points from other international biodiversity-related initiatives, to ensure the activities and benefits of GBIF are well understood and supported within governments and in intergovernmental fora.
* For other Associate Participant organizations, bringing regional, sub-regional and/or thematic priorities into focus within GBIF discussions and planning.
* For Voting Participants, working with relevant authorities within government departments or funding agencies, in collaboration with the Secretariat, to ensure that the financial contribution is paid in full and on time, in order to qualify the country for voting rights; and helping to address any issues related to payment of the contribution.
* In preparing positions, votes, or policy inputs for GBIF governance, the Head of Delegation should consult with the relevant stakeholder community - including organizational nodes and other entities contributing significantly to GBIF-related activities within the Participant’s domain - so that decisions reflect the needs and experience of practitioners as well as national priorities.
* For other Associate Participant organizations, working with relevant authorities within governmental departments and/or funding agencies, in collaboration with the Secretariat, to identify synergies to facilitate co-financing and foster enhanced collaboration, thereby improving the delivery and impact of biodiversity data activities.
****

****
[discrete]
==== Node Manager

After joining GBIF, Participants are also encouraged as soon as possible to appoint a Node Manager, to lead the operational activities of the country or organization in coordinating the mobilization and use of open-access biodiversity data. Detailed guidance is available in this document, but in summary the responsibilities of the Node Manager include:

* Managing the node team that will coordinate biodiversity data mobilization, access and use among relevant stakeholders in the country or organization.
* Collaborating with other node managers and the Secretariat to ensure that the country or organization benefits fully from GBIF participation, including through mentoring arrangements and guidance to share skills and best practices in biodiversity informatics.
* As a member of the GBIF Nodes Committee, attending global nodes meetings (held every two years) and regional nodes meetings (held either annually or every two years) as well as technical workshops and training events.
* Paying close attention to communications from the GBIF Secretariat, including webinars and newsletters, on technical developments and opportunities such as capacity enhancement support calls, and keeping the Secretariat informed about node activities that may be of interest to the wider community.
* Establishing a close working relationship with the HoD to ensure he/she is well informed about the needs and performance of the node, and ideally attending Governing Board meetings as an additional delegate.
* For Node Managers of organizational nodes, coordinating with national nodes within regional and/or thematic communities to ensure that efforts are aligned and mutually supportive.

****
