[[supporting-biodiversity-data-analysis-and-use]]
=== Supporting biodiversity data analysis and use

Examples of services include:

* Facilitating access to biodiversity data by promoting the use of the GBIF infrastructure and/or by maintaining a national or thematic biodiversity data portal
* Promoting the use of correct https://www.gbif.org/citation-guidelines[citation practices] for data accessed through the GBIF network
* Acting as a reference institution for biodiversity information
* Providing support for biodiversity research, through evaluation of data needs and data gaps
* Encouraging interdisciplinary cooperation between scientists, by sharing https://www.gbif.org/resource/search?contentType=dataUse[relevant examples of data use] and through capacity development activities
* Providing support for the compilation, maintenance and publishing of national, sub-national and thematic species inventories and checklists, and the use of these lists to underpin other activities (e.g., conservation work, national reporting)
* Providing support for policy by, for example, offering advice on the designation of biodiversity research priorities, and helping to mainstream the use of of biodiversity data and information in decision-making, spatial planning, biosecurity, conservation and protected area management
* Providing support for national reporting on biodiversity, for example under the Convention on Biological Diversity and other multilateral biodiversity-related agreements
