https://builds.gbif.org/job/doc-effective-nodes-guidance/[image:https://builds.gbif.org/job/doc-effective-nodes-guidance/badge/icon[Build status]]

= Establishing an Effective GBIF Participant Node

This guide includes basic information about two key concepts for GBIF: our Participant nodes and the biodiversity information facilities. The text includes definitions, elements which need to be taken into consideration while building these structures, potential services, requirements and much more.

It is available in multiple languages in both HTML and PDF at https://docs.gbif-uat.org/effective-nodes-guidance/1.0/en/[Establishing an Effective GBIF Participant Node].

This repository served as a prototype for developing GBIF's digital-first documentation described https://github.com/gbif/doc-documentation-guidelines[here]. Its structure was recently updated to align with recommendations embodied in the https://github.com/gbif/doc-template[documentation template].

_This is information *about* this document’s source code.  It is not part of the document._
