[[how-should-a-gbif-participant-select-the-institutional-location-for-a-node]]
=== How should a GBIF Participant select the institutional location for a node?

As discussed above, the institutional location for the node is a critical decision likely to have long-term impacts on its effectiveness in coordinating biodiversity information for the country. Table 1 summarizes the types of institutions previously designated as hosts of GBIF Participant nodes, as well as some of the potential advantages and disadvantages associated with each type of host. Focused mainly on countries rather than organizations, the table does not provide a single recommendation on where to locate a node but can serve as a reference while considering options. These examples are generalized and will vary greatly depending on the specific situation of the Participant. The potential disadvantages in the right-hand column may not be applicable to many countries or host institutions.

In addition to choosing the location of the node, Participants need to decide the position of the node team within the host institution: will it be an autonomous body with an independent mandate, a dedicated section or department of the host institution, or a group of staff members sharing their node responsibilities with other functions? New Participants are advised to consult with colleagues in the network and examine https://www.gbif.org/the-gbif-network[the country profiles on GBIF.org] to help identify the most appropriate model for national circumstances.

As a final note, some GBIF Participants have chosen to divide their node team among several host institutions. In such cases, Participants are advised to designate one institution to coordinate node activity and act as the main contact point for interactions with the GBIF Secretariat and the global network. Only one representative per Participant may be appointed to the Participant Node Managers Committee

[[table-1-generalized-examples-of-the-types-of-institutions-designated-as-hosts-of-gbif-participant-nodes.]]
Table 1: Generalized examples of the types of institutions designated as hosts of GBIF Participant nodes.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

....
.Table
|Potential advantages | Potential disadvantages
|===
|Natural history collections
|
|===
|Existing knowledge of the challenges and requirements of digitizing and managing natural history data
|May take significant effort to demonstrate neutrality (e.g., if it is
a zoological collection, that it can work with other types of collections),
or that it is not competing for digitization funds, etc.

May find difficulty in engaging with other communities holding other types
      of biodiversity data (e.g., observations, ecological data, etc.)

Can make it difficult for the node to serve the needs of some stakeholders
      (e.g., policymakers)
|===
|Ministries of science, environment, et al.
|

|===
|

Very strong mandate and capacity to influence and support policy and decision
      making

Easily aligned with national biodiversity policies, strategies, and programme

|

Challenges to operate at the technical level and to provide technical
      support (e.g., to the scientific community)

Easily affected by political changes

May find difficulties in addressing needs from other ministries (e.g.,
      from science or environment)
|===
|Biodiversity or biological research institutes
|

|===
|

High potential for developing capacity in biodiversity informatics easily and quickly

Full knowledge of the biodiversity-research realm

May have a strong and clear institutional mandate

|May not be perceived as neutral by all stakeholders, depending on how
    the institute fits within the Participant’s overall institutional landscape
    (for example, if there is overlap or competition for resources)

|===
|Research councils or science & technology commissions
|

|===
|

Excellent position to use the Participant node to coordinate, promote
      and facilitate the mobilization of biodiversity data from research

Easily aligned with national research policies, strategies, and programmes

|May not be perceived as neutral by all stakeholders, depending on how
    the institute fits within the Participant’s overall institutional landscape
    (for example, if there is overlap or competition for resources)

|===
|Non-governmental organizations
|

|===
|Flexibility and autonomy
|

Potential lack of mandate, difficulty in formally engaging with government
      institutions

May become dependent on projects and project-based funding


|===
|University departments or faculties
|

|===
|

High potential for developing capacity in biodiversity informatics easily
      and quickly

Potential for aligning the node’s activities with various biodiversity
      research agenda

|May face neutrality issues

May become dependent on projects and project-based funding

|===
|National informatics facilities outside the biodiversity/ biological domain
|

|===
|

Strong position of neutrality

Ready access to technical capacity in informatics

Potentially useful connections with well-funded national priorities on
      innovation and technology

|

Need to invest in staff bringing relevant scientific domain knowledge
      to work effectively with biodiversity data

Need to build contacts and knowledge of relevant institutional networks
|===
....
