[[supporting-biodiversity-data-mobilization]]
=== Supporting biodiversity data mobilization

Examples of services include:

* Organizing biodiversity data within the Participant’s domain to ensure open access to all digitally available biodiversity data
* Promoting and coordinating national investment in the digitization and mobilization of biodiversity information
* Providing a technical infrastructure and support to enable biodiversity data to be published on the Internet and through the GBIF network (including https://www.gbif.org/dataset-classes[sampling-event metadata, occurrence data, checklist data and collections metadata])
* Promoting the benefits of data publishing, for example, through the use of https://www.gbif.org/data-papers[data papers] as a mechanism to gain recognition for sharing of datasets
* Developing a culture of open access and supporting open data requirements mandated, for example, through grant conditions
* Maintaining a collaborative framework between data holders and users, for example, through data sharing agreements that enable data sharing to occur according to agreed terms and encourage data reuse
* Promoting public engagement in biodiversity issues, for example, by supporting citizen science initiatives that mobilize observational data
