[[box-2]]
.Box 2. Stakeholders involved in GBIF activities at the Participant level
****
The https://www.gbif.org/document/80926[GBIF communication strategy] identifies six audiences that represent different groups of stakeholders involved in GBIF activities. While there is some overlap between these groups, each has separate interests and roles to play in contributing to GBIF’s vision. A summary is presented here.

[discrete]
===== The GBIF network

This group includes node managers, staff and governance members; heads of delegation and other Governing Board delegates; advisory committee members; Secretariat staff and contractors; and relevant staff in affiliate organizations.

The key focus of this group is to support participation in the GBIF network through engagement with the other audiences, to support biodiversity data mobilization, management, curation, and use.

[discrete]
===== Data holders

This group includes, among others, current GBIF data publishers; natural history collection curators, informaticians and scientists; field biologists; citizen scientists, voluntary recording networks and observation aggregating sites; authors, editors and publishers of scientific research; custodians of historic biodiversity-related literature and multimedia archives; and organizers and practitioners of surveys and monitoring programmes carried out for public agencies, protected area management and non-governmental organizations.

The key focus of engaging with data holders is to encourage and support biodiversity data mobilization: data digitization, data collection and ultimately publication of their data through the GBIF network.

[discrete]
===== Biodiversity knowledge experts

This group includes zoologists, botanists, mycologists and other species specialists; taxonomists; ecologists; expert networks (e.g. IUCN, Birdlife); and nomenclatural associations.

The key focus of engaging with biodiversity knowledge holders is to support biodiversity data management and curation: continuously improving the quality and fitness-for-use of the data mobilized by the GBIF network, and demonstrating that the work of these groups benefits from strong biodiversity information facilities, at national and global levels.

[discrete]
===== Data users

This group includes ecologists, including macroecologists and biogeographers; species distribution modellers (includes analysts of climate change impacts, invasive species risk, human disease vectors); conservation practitioners, including protected area planners; environmental impact analysts and strategic spatial planning authorities; genetic resources experts (for crop diversity, medicinal compounds etc.); and the ecosystem assessment community.

The key focus of engaging with species occurrence data users is to support biodiversity data use: reusing the data accessible through GBIF to support biodiversity-related sciences and environmental research, ultimately to support evidence based decision making.

[discrete]
===== Decision-makers

This group includes national government ministry and agency officials; research funding agencies; intergovernmental convention officials and national delegates; and global foundations.

The key focus of engaging with funders and executive decision makers is to build support for all GBIF-related activities.

[discrete]
===== Public stakeholders

This group includes educators; students; wildlife enthusiasts; environmentally engaged individuals; and the non-scientific software developer community.

While at the global level these groups are secondary to the others, they may still be key stakeholders involved in national or organizational GBIF activities, for example through citizen science initiatives. Engagement with these groups can build wider support for activities to mobilize biodiversity data and to make biodiversity information about a country freely available to all citizens.
****
