[[introduction7]]
== Further support for establishing a Participant node

Supporting the establishment and further development of Participant nodes and their work is a priority for GBIF as a whole. This guide has introduced some important general considerations in the process of establishing a node. This section explains other opportunities available to gain from experience of the GBIF network in this area.

[[participant-node-exampless]]
=== How can I find examples of Participant nodes?

The https://www.gbif.org/the-gbif-network[country pages on GBIF.org] provide a summarized view of the Participants’ GBIF-related activities. They include information about:

* The Participant’s membership status and date of joining GBIF
* The Participant node’s date of establishment, website and contact information
* An overview of the data published from the country’s institutions, with links to the data publishers and datasets, as well as data published from anywhere in the world about biodiversity located in the country
* Information on the node’s history, vision and mission, structure and national funding
* A list of news items relating to the Participant country and published by the Participant node, as well as links to social media channels operated by the node
* Peer-reviewed research articles citing GBIF as a data source involving authors from the Participant country, as well as articles relating to the country
* Where available, validated lists of introduced and invasive species occurring in the country

https://www.gbif.org/the-gbif-network/participant-organisations[Information about organization Participants] currently displays information about these Participants’ membership, data publishing activity, and links to the node’s website.

Participant nodes are encouraged to share guiding examples with the community, documenting their success stories that others can learn from in establishing or developing their nodes.

Consulting these pages will help to identify the most relevant examples for the specific context of a new GBIF Participant. New Participants are encouraged to use the contact information for the node managers and staff to ask other network members directly for advice in establishing a node.
